version: '3.8'

services:
  app:
    container_name: alumnos_app
    image: alumnos_app:latest
    build: .
    ports:
      - "8502:8501"
    volumes:
      - ./src:/app/src
      - ./src/assets:/app/assets
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - TZ=America/Mexico_City
    restart: unless-stopped
